//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhongTIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cours
    {
        public int id { get; set; }
        public string nameCourse { get; set; }
        public string descriptCourse { get; set; }
        public string detailCourse_1 { get; set; }
        public string detailCourse_2 { get; set; }
        public string detailCourse_3 { get; set; }
        public string meta { get; set; }
        public Nullable<bool> hide { get; set; }
        public Nullable<int> order { get; set; }
        public Nullable<System.DateTime> datebegin { get; set; }
    }
}
