//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhongTIS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PhongTISDB : DbContext
    {
        public PhongTISDB()
            : base("name=PhongTISDB")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Cours> Courses { get; set; }
        public virtual DbSet<Menu> Menus { get; set; }
        public virtual DbSet<ScoreStudent> ScoreStudents { get; set; }
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<Exercise> Exercises { get; set; }
        public virtual DbSet<Question> Questions { get; set; }
        public virtual DbSet<AboutUs> AboutUs1 { get; set; }
    }
}
