//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhongTIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question
    {
        public int id { get; set; }
        public string name_question { get; set; }
        public string answer_one { get; set; }
        public string answer_two { get; set; }
        public string answer_three { get; set; }
        public string answer_four { get; set; }
        public string correct_answer { get; set; }
        public Nullable<int> ExerciseID { get; set; }
        public string meta { get; set; }
        public Nullable<bool> hide { get; set; }
        public Nullable<int> order { get; set; }
        public Nullable<System.DateTime> datebegin { get; set; }
        public string img { get; set; }
    
        public virtual Exercise Exercise { get; set; }
    }
}
