//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhongTIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScoreStudent
    {
        public int id { get; set; }
        public Nullable<int> IDName { get; set; }
        public string scoreTest { get; set; }
        public Nullable<int> IDTest { get; set; }
        public string meta { get; set; }
        public Nullable<bool> hide { get; set; }
        public Nullable<int> order { get; set; }
        public Nullable<System.DateTime> datebegin { get; set; }
    
        public virtual Student Student { get; set; }
        public virtual Exercise Exercise { get; set; }
    }
}
